# Generated by Django 5.2.9 on 2026-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0072_remove_cvederivationclusterproposal_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
